name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: ⚒ Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  test:
    name: 🥁 Test with plone api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps and build
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: docker compose -f "docker-compose.yml" up -d --build && npx wait-on --httpTimeout 20000 http-get://localhost:8080/Plone && npm run test --ci --coverage --maxWorkers=2
